export const eventOptions = [
    // Major Holidays
    "New Year's Eve",
    "Valentine's Day",
    "Easter Party",
    "Mother's Day",
    "Father's Day",
    "4th of July",
    "Labor Day Party",
    "Halloween Party",
    "Thanksgiving Dinner",
    "Christmas Party",
    "Christmas Dinner",
    "Hanukkah Party",
    "Purim Party",
    "Pesach",
    "Rosh Hashanah",
    "Sukkot",
    "Lag Ba'Omer",
    "Shabbat Dinner",
    "Kwanzaa",
    "Chinese New Year",
    "Diwali",
    "Ramadan",
    "Eid al-Fitr",
    "Eid al-Adha",
    "Veterans Day BBQ",
    "Memorial Day BBQ",
    "Juneteenth",
    "St. Patrick's Day",
    "Black Friday",
    "Cyber Monday",
    "Earth Day",
    "Martin Luther King Jr. Day",
    "Mardi Gras",
    "Groundhog Day",
    "Party",
    
    // Life Events
    "Birthday Party",
    "Anniversary Party",
    "Anniversary Dinner",
    "Wedding Reception",
    "Bachelor Party",
    "Bridal Shower",
    "Baby Shower",
    "Gender Reveal Party",
    "Housewarming Party",
    "Retirement Party",
    "Graduation Party",
    "New Job Celebration",
    "Engagement Party",
    "Promotion Celebration",
    "New Home Celebration",
    "Pregnancy Celebration",
    "Going Away Party",
    "Welcome Home Party",
    "Reunion Party",
    "Moving-in Celebration",
    "Adoption Party",
    "Renewal of Vows",
    "Retirement Celebration",
    
    // Niche and Themed Events
    "Game Night",
    "Poker Night",
    "Bonfire",
    "Team Meeting",
    "Lunch",
    "Dinner Party",
    "Pool Party",
    "Pizza Party",
    "Barbecue",
    "Potluck",
    "Cooking Class",
    "Book Club Meeting",
    "Crafting Workshop",
    "Picnic",
    "Concert",
    "Festival",
    "Charity Gala",
    "Film Screening",
    "Comedy Night",
    "Karaoke Night",
    "Yoga",
    "Masquerade Ball",
    "Escape Room Adventure",
    "Pet Adoption Event",
    "Networking Event",
    "Farmers Market Meet-Up",
    "Food Truck Rally",
    "Art Show",
    "Science Fair",
    "Poetry Night",
    "Open Mic Night",
    "Wine Tasting",
    "Beer Tasting",
    "Live Sports Game Viewing",
    "Pottery Class",
    "Dance Class",
    "Hackathon",
    "Cooking Competition",
    "Virtual Meetup",
    "Trivia Night",
    "Chess Tournament",
    "Hiking Trip",
    "Wine and Paint Night",
    "Holiday Decorating Party",
    "Cultural Festival",
    "Candlelight Dinner",
    "Travel Meetup",
    "Camping Trip",
    "Fishing Trip",
    "Meditation Retreat",
    "Volunteer Day",
    "Sports Game",
    "Fashion Show",
    "Ski Trip",
    "Fireworks Show",
    "Open House",
    "Tea Party",
    "Bar Mitzvah",
    "Bat Mitzvah",
    "DIY Workshop",
    "Cosplay Event",
    "Movie Marathon",
    "Tech Conference",
    "Comic Book Convention",
    "Talent Show",
    "Road Trip Meetup",
    "Garden Party",
    "Holiday Party",
    "House Party",
  ];